### ISSUE TITLE
Not found on npm

### ISSUE THREAD

**Issue by Firanolfind** [notchris/phaser3-planck#5]
Is this plugin alive? Could not find it on npm?

**Comment by KingCosmic** [comment]
hey, @Firanolfind this plugin is alive, sadly both me and @notchris are busy in the month of June and haven't finished it up. We're currently working on a 1.0.0 version before we release on npm, you should be able to make a build and use that file if you want to use it rn though.

**Comment by notchris** [comment]
Hey @Firanolfind, this should now be updated / available on npm via: [phaser3-planck](https://www.npmjs.com/package/phaser3-planck)

I'm actively working on this now, so more features coming soon!
